### ISSUE TITLE
Unable to navigate past page 1 of shows/movies

### ISSUE THREAD

**Issue by thebetauser** [groggyegg/plugin.video.dramacool#1] opened 2020-08-30 01:51 UTC
Since the revamp, trying to navigate to page 2 fails for both TV shows and movies. It loops back to page 1 when trying to navigate to page 2

**Comment by groggyegg** [comment] 2020-09-01 00:27
The issue is fixed in version 1.7.0.

**Closed by groggyegg** 2020-09-01 00:27 UTC
