### ISSUE TITLE
Dramacool doesn't work on kodi 20 rc2

### ISSUE THREAD

**Issue by cbizzle14** [groggyegg/plugin.video.dramacool#45] opened 2022-12-27 13:30 UTC
Not my log as I'm not on rc2 yet but it's supposedly coming to xbox so I'll put this here before it's too late.

https://paste.kodi.tv/wiwicopalo

**Comment by groggyegg** [comment] 2023-01-01 21:30
Thanks, it will be fixed in the next release.

**Comment by aarontanx** [comment] 2023-01-17 11:49
Google play store has updated kodi to v20 and this plugin is broken now

**Comment by groggyegg** [comment] 2023-01-18 20:19
> Google play store has updated kodi to v20 and this plugin is broken now

It will be released once the testing is done. Currently there is some bugs found so there will be a delay. And I still need to test the addon with Kodi 18.

**Comment by cbizzle14** [comment] 2023-01-19 14:49
Just putting this out there. Xbox got fully updated to kodi 20 and dramacool is working for me. I've watched 3 episodes so far with no problems

**Comment by groggyegg** [comment] 2023-01-19 21:12
Seems to be different between platform. Anyway, ETA for the next version is probably 21-22/01.

**Comment by megazone23** [comment] 2023-01-20 00:00
> Just putting this out there. Xbox got fully updated to kodi 20 and dramacool is working for me. I've watched 3 episodes so far with no problems

It looks like it is related to the version of python.  I have tried both Android and Windows versions of Kodi 20 and it seems on Windows the python version is 3.8.  This problem seems to happen on a later version of python my guess is on Android it is using python 3.11.

**Comment by ameizeing** [comment] 2023-01-20 07:33
Is this python error in Kodi 20 the same problem highlighted by Dev of Umbrella addon?
https://github.com/xbmc/xbmc/issues/22344
Workaround done for Umbrella & Fen addons, until Kodi team addresses the bug in python 3.11, is to replace ElementTree with Minidom

**Comment by Mycodes2** [comment] 2023-01-20 21:38
Thank you can't wait for the update

**Comment by groggyegg** [comment] 2023-01-21 19:31
> Is this python error in Kodi 20 the same problem highlighted by Dev of Umbrella addon? [xbmc/xbmc#22344](https://github.com/xbmc/xbmc/issues/22344) Workaround done for Umbrella & Fen addons, until Kodi team addresses the bug in python 3.11, is to replace ElementTree with Minidom

Probably unrelated. Errors from the log indicate that the issue is python version.

**Comment by umbrellaplug** [comment] 2023-01-21 21:27
> > Is this python error in Kodi 20 the same problem highlighted by Dev of Umbrella addon? [xbmc/xbmc#22344](https://github.com/xbmc/xbmc/issues/22344) Workaround done for Umbrella & Fen addons, until Kodi team addresses the bug in python 3.11, is to replace ElementTree with Minidom
> 
> Probably unrelated. Errors from the log indicate that the issue is python version.

This is the exact issue we used minidom instead of element tree to avoid using the broken element until it could be fixed.

**Closed** 2023-01-21 22:53 UTC
Labels: bug

**Comment by groggyegg** [comment] 2023-01-21 23:01
> > > Is this python error in Kodi 20 the same problem highlighted by Dev of Umbrella addon? [xbmc/xbmc#22344](https://github.com/xbmc/xbmc/issues/22344) Workaround done for Umbrella & Fen addons, until Kodi team addresses the bug in python 3.11, is to replace ElementTree with Minidom
> > 
> > 
> > Probably unrelated. Errors from the log indicate that the issue is python version.
> 
> This is the exact issue we used minidom instead of element tree to avoid using the broken element until it could be fixed.

The error from OP is related to inspect missing a deprecated method and that has nothing to do with ElementTree 🙂 

`2022-12-27 17:44:53.167 T:21432   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'inspect' has no attribute 'getargspec'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.dramacool/dramacool/addon.py", line 305, in <module>
                                                       plugin()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.xbmcext/./xbmcext.py", line 202, in __call__
                                                       argspec = inspect.getargspec(function)
                                                                 ^^^^^^^^^^^^^^^^^^
                                                   AttributeError: module 'inspect' has no attribute 'getargspec'
                                                   -->End of Python script error report<--`

**Comment by Mycodes2** [comment] 2023-01-21 23:35
Thank you for your time, don't know how to go about fixing it, I'm not savvy with kodi 😞 I'll just wait till hopefully they fix the bug 🙏🏽

**Comment by Mycodes2** [comment] 2023-01-23 14:23
It working now 😘😘😘👏🏽👏🏽👏🏽thank you so much
