### ISSUE TITLE
2.0 new dialogue is broken on Confluence based skin.

### ISSUE THREAD

**Issue by oldpoem** [groggyegg/plugin.video.dramacool#8] opened 2021-03-01 18:12 UTC
In new 2.0 and Matrix.  For any confluence based skin, select "Drama list" option would pop up tiny window for filters.  But whatever picked won't be execute  because OK button went out of bound and no matter blind remote clicks  won't exceute list command.

No ptoblem on Estuary skin though.

**Comment by groggyegg** [comment] 2021-03-09 22:11
Ok, that was something I was worried about when working with custom filter dialog. Could you provide some of the skin name that has this problem? I will check it out when I have the time.

**Comment by oldpoem** [comment] 2021-03-09 22:20
> Ok, that was something I was worried about when working with custom filter dialog. Could you provide some of the skin name that has this problem? I will check it out when I have the time.

I tried Confluence skin and Aeon Nox Silvo  both has this problem.  Both are available on official kodi repo.

**Comment by groggyegg** [comment] 2021-03-14 21:01
A temporary fix has been added 063ae740b0ca898bef6057116be981e093d404e7, which shows the dialog in estuary skin. Adapting the dialog to the current skin seems to be a bit difficult since different skins uses different naming in templates.

**Comment by oldpoem** [comment] 2021-03-14 23:56
Tested on Confluence skin. The ok button is showed and can be select.  But return no results. 1.8.5 on Kodi18  works fine  so it's not server issue.

**Comment by groggyegg** [comment] 2021-03-15 12:33
I can't reproduce the issue. Did you test with version 2.0.1? What is the steps you used to trigger the issue?
Repository updates regularly at 00:00 UTC+2 and might not have the latest version yet.

**Comment by oldpoem** [comment] 2021-03-16 07:09
I tested with 2.0.1  and with these chains give relative results.

Drama list - Japanese Drama - Filter by Char   = Works OK
Drama list - Japanese Drama - Filter by Year   = Return no results.
Drama list - Japanese Drama - Filter by Genres  = Error Dialog Popup
Drama list - Japanese Drama - Filter by Status = Works OK

I mainly use Filter by year.  That's why I encountered no results.

**Comment by groggyegg** [comment] 2021-03-16 10:55
There were some issue with the parser but it should be fixed now in 35c93cc7b10f96c90acf93c3f69df79d2694a338.

**Closed** 2021-03-25 20:36 UTC
Labels: bug
