### ISSUE TITLE
3.2.7 doesn't load video list

### ISSUE THREAD

**Issue by mikeyipdotcom** [groggyegg/plugin.video.dramacool#70] opened 2024-01-02 13:28 UTC
Am using the Dramacool 3.2.7 on Kodi.
Since mid-December when the site went down, the app in Kodi stop loading videos/lists except for the main groups.

When select Recently Watched or any of the links, it just get stuck on the loading icon and not go anywhere.

1. In Kodi
2. Click on Dramacool
3. Select link (Recently Watched)...
4. loading icon just froze and not load anything.

Kodi doesn't produce any log file for me to share here.

**Comment by groggyegg** [comment] 2024-01-02 19:17
Can’t reproduce the issue. What OS are you using?

**Comment by mikeyipdotcom** [comment] 2024-01-05 01:44
> Can’t reproduce the issue. What OS are you using?

Am currently on Kodi v20.2 (Nexus). 
It loads your main page fast.
Trying to go into the show list are the one where the loading icon appears and doesn't do anything else after. 

So am stumped, have uninstalled Kodi, reinstalled the Dramacool from your lime repo as per usual.

**Comment by groggyegg** [comment] 2024-01-05 12:34
Ok, it might be an issue with domain. Could you install “Kodi Logfile Uploader” from repository and upload the log file? Easier to debug if possible.

**Comment by groggyegg** [comment] 2024-01-13 11:55
Just looking at the log I can't find any reason why it would freeze. But you do have some other errors such as `error <general>: CCurlFile::Stat - <http://mirrors.kodi.tv/addons/nexus/...> Failed: Timeout was reached(28)`. Not sure if it's related.

Could you turn on debug mode and try again? https://kodi.wiki/view/Settings/System/Logging#Debug

**Comment by wongeujin** [comment] 2024-03-02 09:37
same issue here. any fixes? dramacool gets stuck at the gear icon. no errors whatsoever, just cannot access. anything to do with the site changing names to runasian?

**Comment by groggyegg** [comment] 2024-03-09 10:53
> same issue here. any fixes? dramacool gets stuck at the gear icon. no errors whatsoever, just cannot access. anything to do with the site changing names to runasian?

 Try change the domain in settings and see if it fix the problem

**Comment by groggyegg** [comment] 2024-04-17 19:30
Is this still an issue?

**Comment by mikeyipdotcom** [comment] 2024-04-19 00:44
> Is this still an issue?

Presently, the loading is slow but bearable (just have to wait about 5-10minute each time depending on no. of contents) to load each page after changing the link to the new ones that Dramacool posted up in Twitter.

Not sure why this is happening as previously, it was quite instantaneous, could be possible be some throttling done by the local ISP? (Malaysian user here)

**Comment by groggyegg** [comment] 2024-04-19 18:45
> Presently, the loading is slow but bearable (just have to wait about 5-10minute each time depending on no. of contents) to load each page after changing the link to the new ones that Dramacool posted up in Twitter.
> 
> Not sure why this is happening as previously, it was quite instantaneous, could be possible be some throttling done by the local ISP? (Malaysian user here)

Have you tried using another dns for example google's dns?
https://developers.google.com/speed/public-dns

It can be configured either in router or Windows/Linux

**Comment by groggyegg** [comment] 2024-06-06 12:41
Closing this as it seems to be unrelated to addon.

**Closed by groggyegg** 2024-06-06 12:41 UTC
