### ISSUE TITLE
Couldn't Resolve Server Error

### ISSUE THREAD

**Issue by shwaDP** [groggyegg/plugin.video.dramacool#15] opened 2021-07-01 21:39 UTC
Hello, 
I am using Dramacool with the Kodi 19.1 Matrix version on my 4k Firestick.
When selecting a kdrama show to watch (ex. The Penthouse 3), all of the servers are either "Unsupported server" or "Couldn't resolve server error".
Is this an issue that can be resolved through my end? And if not, do you know the reason as to why the servers are not working, and if it's just a temporary issue that can be solved?

**Comment by groggyegg** [comment] 2021-07-02 16:07
Duplicate of #14
Make sure you have latest script.module.resolveurl (v5.1.35)

**Closed by groggyegg** 2021-07-02 16:07 UTC
