### ISSUE TITLE
Doesn't work on kodi 19

### ISSUE THREAD

**Issue by laurie026** [groggyegg/plugin.video.dramacool#9] opened 2021-04-30 17:11 UTC
Can you do the update please.

**Comment by groggyegg** [comment] 2021-05-01 20:22
The last time I tested, the addon worked in Kodi 19 and I haven't seen any change in the website that would break this addon. Please provide more information on the issue such as:

- The steps to reproduce the issue.
- The addon version.
- The platform used.

**Comment by ong-andrew** [comment] 2021-06-09 15:56
groggyegg. First of all, great work on this addon.

Works great on my Linux PC, but not on my Android TV box. 

` requests.exceptions.ConnectionError: HTTPSConnectionPool(host='watchasian.cc', port=443): Max retries exceeded with url: /category/korean-drama (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7b95846e30>: Failed to establish a new connection: [Errno 110] Connection timed out'))
`

To be sure, I've mirrored on my TV box all the dependencies that appears on my Linux PC.

If you'd like access to the full session log, please click [here](https://bit.ly/3500w9g).

**Comment by groggyegg** [comment] 2021-06-20 11:29
I'll close this issue since I haven't found any issue with the addon and it might just be a ISP problem.

**Closed by groggyegg** 2021-06-20 11:29 UTC
